// Generated by CoffeeScript 1.8.0
(function() {
  var addRainbow, hookEvents;

  addRainbow = function(container) {
    var child;
    child = document.createElement("div");
    child.className = "rainbow";
    container.appendChild(child);
    return hookEvents(child);
  };

  hookEvents = function(element) {
    return element.onclick = function() {
      if ((element.className.indexOf('selected')) !== -1) {
        return element.className = 'rainbow';
      } else {
        return element.className = 'rainbow selected';
      }
    };
  };

  window.rainbow = addRainbow;

}).call(this);
