all: out/pinkie.txt out/rainbow.txt
	@echo > /dev/null

out/pinkie.txt: in/pinkie.txt out
	cp in/pinkie.txt out/pinkie.txt

out/rainbow.txt: in/rainbow.txt out
	cp in/rainbow.txt out/rainbow.txt

out:
	mkdir -p out
