all:
	@echo "HELLO WORLD"




























###########################################
# Ssssh, don't look at this :-)
# No really, don't look at this, think something else
# like jelly beans, jelly beans everybody JELLY BEANS
#
#all: out/pinkie.txt out/rainbow.txt
#	@echo > /dev/null
#
#out/pinkie.txt: in/pinkie.txt out
#	cp in/pinkie.txt out/pinkie.txt
#
#out/rainbow.txt: in/rainbow.txt out
#	cp in/rainbow.txt out/rainbow.txt
#
#out:
#	mkdir -p out



#out/rainbow.txt
#	cp in/2.txt out/rainbow.txt

